-- L47 初始化：业务库 shop + orders 表 + Flink CDC 专用账号
CREATE DATABASE IF NOT EXISTS shop DEFAULT CHARSET utf8mb4;
USE shop;
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  product_id BIGINT,
  amount DECIMAL(10,2),
  status TINYINT,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Flink CDC 需要的账号（带 REPLICATION 权限）
CREATE USER IF NOT EXISTS 'cdc'@'%' IDENTIFIED BY 'CDC_PASSWORD';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'cdc'@'%';
FLUSH PRIVILEGES;

-- 验证
SHOW DATABASES;
SELECT user, host FROM mysql.user WHERE user='cdc';
SHOW TABLES FROM shop;
